// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SkyWalker.Dal.DBContext;

namespace User.API.Migrations
{
    [DbContext(typeof(SkyWalkerDbContext))]
    [Migration("20180522150134_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("SkyWalker.Dal.Entities.AppUser", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Avatar")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Sex");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserPassWord")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id", "UserId");

                    b.ToTable("AppUser");
                });
#pragma warning restore 612, 618
        }
    }
}
